<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <EmbeddedResource Include="../App_Doc/events.style-settings.md" Link="App_Doc/events.style-settings.md" LogicalName="CircleSpaceCoordinator.EventListStyle.json" />
    <AssemblyMetadata Include="EventListStyleSource" Value="$([System.IO.Path]::GetFullPath('$(MSBuildProjectDirectory)/../App_Doc/events.style-settings.md'))" Condition="'$(Configuration)' == 'Debug'" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../CircleSpaceCoordinator.EditorClient/CircleSpaceCoordinator.EditorClient.csproj" />
    <ProjectReference Include="../CircleSpaceCoordinator.TableIO/CircleSpaceCoordinator.TableIO.csproj" />
    <ProjectReference Include="../CircleSpaceCoordinator.StationeryUI/CircleSpaceCoordinator.StationeryUI.csproj" />
  </ItemGroup>
</Project>
