<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.36.1" />
    <PackageReference Include="Grpc.Core.Api" Version="2.83.0" />
    <PackageReference Include="Grpc.Tools" Version="2.83.0" PrivateAssets="all" />
    <Protobuf Include="Protos/engines.proto" GrpcServices="Both" />
  </ItemGroup>
</Project>
